### ISSUE TITLE
Tailwind inline CSS not working

### ISSUE THREAD

**Issue by Music47ell** [timlrx/rehype-prism-plus#2]
While testing the plugin locally, I tried replacing the CSS class name with Tailwind CSS classes but it didn't work. 

For example:
https://github.com/timlrx/rehype-prism-plus/blob/7a6e7cd994947edaae26836fe0fedcf3fb344855/index.js#L63

I tried replacing that line with this:
```js
properties: { className: ['pl-4 -mx-4 border-l-4 border-gray-800'] },
```

Do you have any idea why it didn't work? And how to make it work?

**Comment by timlrx** [comment]
I think it should work but if it does not it might be due to how purgeCSS works, as it is not able to infer that these class names will be used. You can try adding them to the safelist in tailwind config and verify that it works. Otherwise, if you inspect the code using the browser console, do you see those class names injected?

**Comment by Music47ell** [comment]
When using the console to inspect the HTML output, I do see the classes as shown in the screenshot below.

<img width="515" alt="Screen Shot 2021-07-04 at 8 01 27 PM" src="https://user-images.githubusercontent.com/5708563/124393340-b453dc80-dd02-11eb-82aa-656125266d46.png">

But, not all Tailwind classes are applied.

For example: I don't see the blue border `border-l-4 border-primary-500` or the line number `before:pr-4 before:-ml-2 before:text-gray-400 before:content-[attr(line)]` even though the classes are in the HTML output.

<img width="498" alt="Screen Shot 2021-07-04 at 8 00 37 PM" src="https://user-images.githubusercontent.com/5708563/124393313-82db1100-dd02-11eb-888d-a66c07ac390f.png">

**Comment by timlrx** [comment]
Just tried and verified that it would not work  - reason being that mdx-bundler compiles all the code to HTML and CSS but it would not know about the tailwind tokens. One could possibly add tailwindcss and postcss to the build process so that it is aware but otherwise it only recognises them as css class names. The application itself has to map those class names to styles and add the appropriate style sheet.

**Comment by Music47ell** [comment]
What I want is to add a Tailwind option. Set it to true, and you wouldn't need to copy/paste the [CSS style](https://github.com/timlrx/rehype-prism-plus#styling) you mentioned here. 

For example:
```js
[require('rehype-prism-plus'), { ignoreMissing: true, tailwind: true }]
```

I've tried it locally but Tailwind CSS classes didn't work.

**Comment by timlrx** [comment]
the way most plugins do it is to export a css file that the user can than import directly

**Comment by Music47ell** [comment]
I guess copying the css styles is the better option 😂
